### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by fpozon** [ngiann/ConvolvedGaussianProcessesExperiments#1]
If I am not mistaken, the data are more in favour of mattern12 with an accretion of 30% (green curve). Other values (blue and red solid curves) are also plausible, but the probability is somewhat lower. The mattern32 is less likely.
One question: is there a visible difference in the fit of the light curves? for all 4 experiments?
Could you try to include the plot of the light curve fit for the "best" black hole mass for each experiment?

**Comment by ngiann** [comment]
I updated the results. It seems that there is no difference between matern12 and matern32.
RBF is tiny bit worse.
Somewhat surprsing that both 10% and 30% eddington fraction are better than 20%.
I will get on with plotting the best fits for each combination.

**Comment by ngiann** [comment]
I uploaded two images for the fitted lightcurves. I chose only two cases, matern12+10% and rbf+20%, so as not to clutter the page with figures. I only notice slight differences between them.

**Comment by fpozon** [comment]
> 

I am a bit confused with the first diagram. The y-axis is the probability right? then I can see that the matern12 are the solid lines and have the highest probability. However the matern32 are the dash lines and all have lower probability. But from your comment you say that there is no difference between matern12 and matern32. Then I got confused.

**Comment by fpozon** [comment]
Another comment: Would it be possible that you can also output after the fitted light curves, the centroid of the transfer function to know the predicted time-delay? between the light curves.

**Comment by ngiann** [comment]
> > 
> 
> I am a bit confused with the first diagram. The y-axis is the probability right? then I can see that the matern12 are the solid lines and have the highest probability. However the matern32 are the dash lines and all have lower probability. But from your comment you say that there is no difference between matern12 and matern32. Then I got confused.

The y axis is indeed probability and the x axis is mass. 

This plot shows the mass probability distribution for each kernel-"eddington fraction" combination.
These probability distributions are combination dependent. Equivalently one can state that these are probability distributions conditioned on the combination and should therefore be interpreted as answering the following question: given that a combination is true, how is mass distributed?
 
So these probability distributions tell us how mass is distributed on the assumption that a given combination is true (i.e. assume that the kernel-"eddington fraction" are the true choices/values that generated the observed data).

However, they do not tell us how likely the combinations themselves are. They only tell us what the likely masses are given that a combination is true.

One can also understand it like this: if we denote the kernel-eddington combination by θ and data by D, then the depicted probability distributions are p(mass|θ, D). This is the conditional probability of mass given a particular combination θ and the observed data D. However, the probability distribution that you are referring to is p(θ|D), i.e. the conditional probability of mass given the observed data D. This distribution is given as the [table](https://github.com/ngiann/ConvolvedGaussianProcessesExperiments/blob/main/Mrk279_2019.md#joint-probability-for-kernel-eddington-fraction) under the title "Joint probability for kernel, eddington fraction".

**Comment by ngiann** [comment]
> Another comment: Would it be possible that you can also output after the fitted light curves, the centroid of the transfer function to know the predicted time-delay? between the light curves.

When I fit the light curves, I work out the most likely mass (mode of the mass probability distributions) for the respective combination I am plotting. 

For the combination matern12 and 10%, the most likely mass is 1.494869e+08.
For the combinarion rbf and 20%, the most likely mass is 1.037225e+08.

I suppose these values completely specify the transfer functions you need?
